bidirectional: false
dropout: 0.5
feature_size: 31
hidden_size: 200
l2: 0.001
loss: cross_entropy
lr: 0.0001
lr_scheduler: null
lr_scheduler_args: null
model_type: mtand
n_state: 2
n_timesteps: 48
optim: adam
regres: true
rnn: GRU
